version: '3.9'

services:
  nginx:
    build:
      context: .
      target: nginx_base
    volumes:
      - ./:/srv/app:ro,cached
      - php_socket:/var/run/php
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - app

  php:
    image: ${IMAGES_PREFIX:-}app-php
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    networks:
      - app

volumes:
  php_socket:

networks:
  app:
    driver: bridge
